### ISSUE TITLE
Enhancement: Support `msgspec` data modelling 

### ISSUE THREAD

**Issue by JacobCoffee** [DanCardin/cappa#113]
## Description

Support [msgspec](https://jcristharif.com/msgspec/) library for things like `Struct` for building.

## Why

Msgspec is [*fast*](https://jcristharif.com/msgspec/benchmarks.html), some people don't have to download extra libraries (in my case, at least... `msgspec` is already bundled with my libraries as a dependency)

**Comment by DanCardin** [comment]
So long as it supports enough introspection abilities (dont see anything obvious in the docs) to extract the information cappa needs, shouldn't be too difficult

**Comment by DanCardin** [comment]
@JacobCoffee I dont suppose you have any real-world code ready to consume this PR, to make sure it works as intended, before I merge?

If not, I can always follow up in bugfix PRs, as this is net-new behavior anyway

**Comment by JacobCoffee** [comment]
Not at the moment! 😬
