### ISSUE TITLE
bug/ux: version with long=True shows actual version as long option

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#12]
```python
import cappa

@cappa.command()
class CommandMain:
    whatever: str = ""
    def __call__(self):
        pass

cappa.invoke(
    CommandMain,
    argv=["hello", "-h"],
    version=cappa.Arg(
        "0.1.0",
        short="-V",
        long=True,
        help="Print the version of the program and exit.",
    ),
)
```

Output:

```text
usage: [-V] [-h] [whatever]

Options:
  -V, --0.1.0  Print the version of the program and exit.

Arguments:
  whatever

Help:
  -h, --help   Show this message and exit.
```

I realize there's no easy way to infer the long argument (maybe `"version"`?), so maybe `long=True` should be forbidden here? It works fine if I manually specify `long="--version"` :slightly_smiling_face:

**Comment by DanCardin** [comment]
woops! sad oversight.

Since the default is already `--version`, 0.8.1 makes it default to --version when it's given as True.

(also thanks for all the reports! all my downstream uses have very consistent usage patterns that are apparently not exercising these paths :P)

**Comment by DanCardin** [comment]
Sidebar, if I happen to catch your attention: I'm planning on swapping the default to the [native cappa backend](https://cappa.readthedocs.io/en/latest/backends.html) soonish. And you're my main external consumer so far.

If you're interested in colored/prettier help-text and/or CLI auto completions, and wanted to help exercise the native backend, I'd be much obliged! tl;dr `cappa.invoke(..., cappa.backend)`

**Comment by pawamoy** [comment]
Sure! I'm definitely interested in auto-completion and colors. I actually tried to install Cappa with the `color` extra (as mentioned in the docs) but it seems this extra does not exist. I'll try the native backend and report any issue :slightly_smiling_face:

**Comment by DanCardin** [comment]
woops! It's left over in the api docs pulled out of the docstrings 😮‍💨. I only updated the actual hand-written color/rich page, sigh
