### ISSUE TITLE
zsh completion wrong

### ISSUE THREAD

**Issue by euri10** [DanCardin/cappa#121]
it seems the generated function happens a newline before the `--complete` that breaks the completion, here's a diff between a workin version and the on-working gnerated currently:

```diff
❯ diff ~/.oh-my-zsh/custom/plugins/yadr/yadr.plugin.zsh ~/.oh-my-zsh/custom/plugins/yadr/yadr.plugin.zsh.ok
7,8c7
<     completions=("${(@f)$(env COMPLETION_LINE="${words[*]}" COMPLETION_LOCATION=$((CURRENT)) yadr 
< --completion=complete)}")
---
>     completions=("${(@f)$(env COMPLETION_LINE="${words[*]}" COMPLETION_LOCATION=$((CURRENT)) yadr --completion=complete)}")
```

**Comment by DanCardin** [comment]
Is this `yadr` public?

On at least the current version of the code, I just ran `hera --completion generate` and got:

```
❯ hera --completion generate
warning: The `hera` CLI is a work-in-progress, subject to change at any time!
#compdef hera

_hera_completion() {
    local -a completions
    (( ! $+commands )) && return 1

    completions=("${(@f)$(env COMPLETION_LINE="${words[*]}" COMPLETION_LOCATION=$((CURRENT)) hera --completion=complete)}")

    if [[ -n "$completions" ]]; then
        if [[ "${completions[1]}" == "file" ]]; then
            _files
        else
            _describe 'options' completions
        fi
    fi
}

if [[ $zsh_eval_context[-1] == loadautofunc ]]; then
    _hera_completion "$@"
else
    compdef _hera_completion hera
fi
```
i.e. sans newline

looking at https://github.com/DanCardin/cappa/blob/main/src/cappa/completion/shells.py#L40, I cant see how that'd result in there being a newline, but i guess it does correspond to the actual newline location...

**Comment by euri10** [comment]
for anyone interested and as post-mortem, the Shell integration checkbox was clicked and caused this issue, which is insane to be fair....

![20240610_1509_558x604_1718024999](https://github.com/DanCardin/cappa/assets/1104190/9c6bd67e-2d6d-4322-a148-c739aa89046e)
