### ISSUE TITLE
feedback: Differences with argparse

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#14]
### 1

One small difference with argparse I noticed, is that with argparse you can pass arguments without the program path to `parser.parse_args()`, for example `parser.parse_args(sys.argv[1:])`, while with Cappa you must include the program path: `cappa.invoke(CommandMain, argv=sys.argv)`.

It's not that problematic, but it does break my long standing pattern of using `sys.argv[1:]` in my `__main__` modules:

```python
"""Entry-point module, in case you use `python -m insiders`.

Why does this file exist, and why `__main__`? For more info, read:

- https://www.python.org/dev/peps/pep-0338/
- https://docs.python.org/3/using/cmdline.html#cmdoption-m
"""

import sys

from insiders.cli import main

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
```

It's easily fixed though:

```python
def main(args: list[str] | None = None):
    return cappa.invoke(
        CommandMain,
        argv=args and ["progname", *args],
    )
)
```

...so don't bother too much changing that. A note in the docs would probably be more than enough (for example in a table that compares it to argparse).

**Comment by pawamoy** [comment]
### 2

With argparse backend:

```python
def main(args: list[str] | None = None):
    return cappa.invoke(
        CommandMain,
        argv=args and ["progname", *args],
    )
)
```

```console
$ python -m progname -h
usage: __main__.py [-h] ...
# not great
```

With Cappa backend:

```python
def main(args: list[str] | None = None):
    return cappa.invoke(
        CommandMain,
        argv=args and ["progname", *args],
        backend=cappa.backend,
    )
)
```

```console
$ python -m progname -h
usage: progname [-h] ...
# much better!
```

**Comment by DanCardin** [comment]
1. 

Yea hmm. I now see that argparse always only take `argv[1:]` internally, but then requires `prog` or hardcoded `argv[0]` inside the parser in order to do help text generation. I think I prefer the current behavior of cappa at a glance.

So long as the behavior is consistent between the argparse and cappa backends (...which it seems like it should be, given that inside `cappa`, I do `argv[1:]` before sending it into `parse_args), I agree. I'll just write a note in the docs.
---
2. 

i guess in combination with difference 2 though...I could...add an optional prog argument, and copy argparse's behavior of only chopping off the first arg when its sourced from `sys.argv` directly...

---

3. yea clear bug. should be easy enough to fix

**Comment by pawamoy** [comment]
> i guess in combination with difference 2 though...I could...add an optional prog argument, and copy argparse's behavior of only chopping off the first arg when its sourced from sys.argv directly...

I don't have a strong opinion. I like the consistency of having to declare a name on my main command class. I like less the `argv=args and ["progname", *args]` trick. Whatever elegant way you can find to reduce duplication is fine by me :slightly_smiling_face:

**Comment by pawamoy** [comment]
Ah, in fact, I would really prefer **not** passing the exec path to the `main` function, because if I want to call it from somewhere else, I *definitely* do not want to have to pass a fake exec path just to call the CLI:

```python
from insiders.cli import main

main(["arg1", "arg2"])  # good
main(["whatever", "arg1", "arg2"])  # feels redundant and unnecessary
```

Same for my tests modules.

**Comment by pawamoy** [comment]
To summarize:

```python
@capp.command(name="progname")  # feels consistent
argv=args and ["progname", *args]  # not a fan but OK
sys.exit(main(sys.argv))  # no go
```

**Comment by DanCardin** [comment]
I **think** https://github.com/DanCardin/cappa/pull/16 should address all three issues.

* "prog" should be being set by command name always
* implicit argv pulls off the 1st item
* explicit argv expects no prog ("breaking" change)

If you're up to testing my branch before I release it, feel free!
