### ISSUE TITLE
feedback: Native backend output

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#15]
First of all, great work! It's looking good :slightly_smiling_face: 
I'll add numbers to the items to ease discussion.

---

Main command:

![cappa1](https://github.com/DanCardin/cappa/assets/3999221/18d593b8-b7fc-4897-a177-6f93045db787)

1. :thinking: I think I'd prefer not showing both option forms in the first usage line: just the short form, or just the long form (personal preference on just the short form).
2. :thinking: Maybe keep using the convention of UPPERCASE for option values? COMPLETION in this example. EDIT: actually I [can't prove](https://stackoverflow.com/questions/9725675/is-there-a-standard-format-for-command-line-shell-help-text) this is a convention, I might just be mistaken.
3. :thinking: Maybe use a different color for the curly braces (white, just like brackets?) and the available commands (blue/whatever, just not the same as completion in the screenshot above?).
4. :bug: A dot is missing (probably) in the `--completion` help, after "source". The valid options are duplicated? See PR #19

---

Subcommand:

![cappa2](https://github.com/DanCardin/cappa/assets/3999221/e5bebdd2-718f-4b2e-a7a1-9bf9525bde02)

1. :thinking: Again, maybe show only one option form in the first usage line.
2. :bug: The subcommand name is missing? `Usage: insiders -n ...` instead of `Usage: insiders create -n ...`. I think argparse itself suffers from the same thing.
3. :heavy_check_mark: Good call on showing the options value/placeholder only once, contrary to argparse :+1: (for example `namespace` and `repo` in the screenshot). Argparse takes so much horizontal space for these...
4. :heavy_check_mark: Good call adding `[]` around optional flags too, it avoids having to look back up to know if an option is required or not :+1:
5. :thinking: I see that default values are not shown, contrary to argparse. I'm not sure I'd want to change that: I don't like that the argparse backend adds the default value at the end, *after* the dot of my description. Also, it's hardcoded in english, which might not be desirable in some situations. If we are to add an option to show default values with the Cappa backend, it should use specific colors and notation, something like:

```
[-t/--copier-template]  Whether to ... template. =False
```

(`=` being bold white, `False` being bold pink for example)

**Comment by pawamoy** [comment]
I realize the colors are not hardcoded and depend on the terminal theme, so don't pay attention to the color names I used in my post (nor the colors in the screenshots ^^)

**Comment by pawamoy** [comment]
If the Cappa backend uses Rich, it could be nice to render longer description as Markdown:

```python
@cappa.command(name="create")
class CommandCreate:
    """Create public/insiders repositories.

    This command will do several things:

    - Create public and insiders repositories on GitHub
        (using the provided namespace, username, repository name, description, etc.).
    - Clone these two repositories locally (using the provided repository paths).
    - Initialize the public repository with a README and a dummy CI job that always passes.
    - Optionally initialize the insiders repository by generating initial contents
        using the [Copier PDM template](https://github.com/pawamoy/copier-pdm).
    """
```

Current:

```
Create public/insiders repositories. This command will do several things:

- Create public and insiders repositories on GitHub
    (using the provided namespace, username, repository name, description, etc.).
- Clone these two repositories locally (using the provided repository paths).
- Initialize the public repository with a README and a dummy CI job that always passes.
- Optionally initialize the insiders repository by generating initial contents
    using the [Copier PDM template](https://github.com/pawamoy/copier-pdm).
```

As Markdown:

```
Create public/insiders repositories.                                                                                                                                                 

This command will do several things:                                                                                                                                                 

 • Create public and insiders repositories on GitHub (using the provided namespace, username, repository name, description, etc.).                                                   
 • Clone these two repositories locally (using the provided repository paths).                                                                                                       
 • Initialize the public repository with a README and a dummy CI job that always passes.                                                                                             
 • Optionally initialize the insiders repository by generating initial contents using the Copier PDM template.
```

(screenshot for colors)

![richmarkdown](https://github.com/DanCardin/cappa/assets/3999221/c170825a-a3f8-46bc-bcff-25eb23cffa87)

**Comment by pawamoy** [comment]
I'm now adding more subcommands, and noticing this help:

```
               Subcommands                                                                                                                                              
             {create,pypi}  The selected subcommand. 
```

Could it show each command on a separate line instead, using its docstring summary as description?
Otherwise the Subcommands paragraph is not super useful.

**Comment by DanCardin** [comment]
Thanks for all the feedback, pretty sure I agree with all of it

**Comment by DanCardin** [comment]
Lmk if anything looks amiss in https://github.com/DanCardin/cappa/pull/32, I think it addresses each line item (except the one you already fixed 😆) in addition to removing the right justify

**Comment by pawamoy** [comment]
I'll try it in a few minutes and report back!

**Comment by pawamoy** [comment]
Sorry, I got lost in my attemps at debugging something else. But I did try this PR and everything looks good :slightly_smiling_face:
