### ISSUE TITLE
Confusing/unclear parsing output

### ISSUE THREAD

**Issue by chuckwondo** [DanCardin/cappa#2]
Given the following in a file named `example.py`:

```python
import cappa

@cappa.command
class Example:
    x: int

cappa.parse(Example)
```

When I run the following:

```plain
python example.py a
```

I get the following output:

```plain
Traceback (most recent call last):
    ...
    value = arg.parse(value)
            ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'a'
```

I would expect something a bit more helpful than a traceback that includes no information about the argument for which parsing failed. Obviously, since there's only 1 argument in this example, I know which one it's referring to, but for a more complex case, this is likely far from helpful in pinpointing the problem.

I would expect to see output more like the following, without any traceback:

```plain
ERROR: argument x: invalid literal for int() with base 10: 'a'
```

As an attempted workaround, I added a parser:

```python
def parse_x(s: str) -> int | NoReturn:
    try:
        return int(s)
    except Exception as e:
        raise cappa.Exit(str(e), code=1) from None


@cappa.command
class Example:
    x: Annotated[int, cappa.Arg(parse=parse_x)]
```

However, this time, running `python example.py a` produced absolutely no output at all, even though the exit code was properly set to `1`. Producing no output is even worse than producing a confusing traceback because the traceback at least makes it obvious that something went wrong.

Am I using the library incorrectly?

**Comment by DanCardin** [comment]
You're not using the library incorrectly! Apparently I've been primarily testing happy paths for inference parsing. I think this will just mean wrapping the parsing and internally doing what you're doing.

I should be able to quickly add this to the 0.7 release I'm staging for release as I write this.

**Comment by chuckwondo** [comment]
Great! Thanks for the prompt reply. And thanks for `cappa`! I've always found `click` and `typer` to be too much clutter, so `cappa` makes for a much cleaner and clearer separation of things.

**Comment by DanCardin** [comment]
No problem, and thanks for the kind words (twas my exact reason for the lib!). And thanks for the repot!

v0.7 should, make your original testcase output: "Invalid value for 'x' with value 'foo': invalid literal for int() with
base 10: 'foo'". It should also cause explicit `Exit` calls to always output the provided string.

It did also come with a number of dependency changes and other (relatively minor) breaking changes, hopefully not a problem!

**Comment by DanCardin** [comment]
Feel free to reopen or submit another issue if 0.7 doesnt fix your issue. And thanks again for the report!
