### ISSUE TITLE
bug: More short arg value parsing cases

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#28]
Follow-up of #20. Sorry, I should have thought about adding more tests/examples.

These cases are failing:

```console
% python cappabackend.py -a"hello world" 
Option 'arg' requires an argument.
```

```console
% python cappabackend.py -ahello\ world 
Option 'arg' requires an argument.
```

They're really the same thing, the shell parses `-a"hello world"` and `-ahello\ world` the same way, as a single string whose value is `-ahello world` once in the executing program (in `sys.argv`).

**Comment by pawamoy** [comment]
Actually a simple `-ahello` fails too, with Cappa 0.8.6, while `-a1000` works fine. I suppose both cases are handled differently because the first uses letters and the second numbers? They both should be treated as arbitrary characters without any difference.

**Comment by pawamoy** [comment]
Note how argparse eats up the whole string:

```console
% python cb.py "-a hello -a world"
 hello -a world
```

**Comment by DanCardin** [comment]
hrmmmm. I think this is the key

> When encountering a short option that expects a value

as implemented, it is assuming all options until the last one accept no arguments. hopefully this just means checking the num_arginess of the args as it identifies them as valid
