### ISSUE TITLE
feat/question: API to navigate the CLI (commands, options)

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#35]
Following #33, I'd like to expose a use-case I have for a proper API to navigate the constructed CLI and its options/subcommands.

When writing documentation for my projects, I like to include a page which describes the CLI. Instead of copy-pasting the help message obtained with `progname -h`, and failing to update it when the CLI changes, I like to auto-generate the page's contents (for example with Markdown Exec) by inserting the help message at build time.

Better than just inserting the formatted help message in a code block, I like to iterate over the CLI commands and options to build actual Markdown/HTML. A concrete example is the reference for Griffe's CLI: https://mkdocstrings.github.io/griffe/cli_reference/. If you look at the page source, you can see how I iterate over the argparse parser to build a Markdown string (that is rendered to HTML later in the process): https://github.com/mkdocstrings/griffe/blob/main/docs/cli_reference.md.

I was wondering if such iteration of the commands and options was possible with Cappa and its native backend. If yes, could you show an example here, or maybe add it to the docs? If not, could we discuss how we could expose the necessary API bits to allow such use-cases :slightly_smiling_face:?

**Comment by DanCardin** [comment]
Sure, so the cappa `Command` you get back from `cappa.base.collect` is the same structure the code uses to iterate everything during parsing, as well as generate help text, so it's pretty well solidified. the `Command.arguments` will contain all the arguments which'll be of type `Arg` or `Subcommand`.

It was pretty straightforward to do a naive port of your linked function, although I did remove some special handling you included for argparse because I wasn't sure whether it was relevant to cappa or not, but:

```python
import cappa
from cappa.base import collect
from cappa.help import generate_arg_groups


def render_parser(command: cappa.Command, title: str, heading_level: int = 2) -> str:
    """Render the parser help documents as a string."""

    result = [f"{'#' * heading_level} {title}\n"]
    if command.description:
        result.append("> " + command.description + "\n")

    for name, group in generate_arg_groups(command):
        result.append(f"{name.title()}:\n")
        for arg in group:
            if isinstance(arg, cappa.Subcommand):
                for option in arg.options.values():
                    result.append(
                        render_parser(option, option.real_name(), heading_level + 1)
                    )
                continue

            opts = [f"`{opt}`" for opt in arg.names()]
            if not opts:
                line = f"- `{arg.name}`"
            else:
                line = f"- {', '.join(opts)}"

            line += f" `{arg.name}`"
            line += f": {arg.help}"
            if arg.default is not cappa.Arg.default:
                default = str(arg.default)
                line += f" Default: `{default}`."
            result.append(line)
        result.append("")

    return "\n".join(result)


command = collect(Example)
print(render_parser(command, "example"))
```

This is basically what the help text formatter is already doing but rendering to rich objects.

Only "issue" is that I wouldn't really consider `generate_arg_groups` a public function. but that's really just doing the work of splitting out the different sections of the help text, which you may or may not even want. But it's just a glorified `functools.groupby` loop over `command.arguments`, so you could remove that in any case.

**Comment by DanCardin** [comment]
With that said, in my previous comments i'd mentioned `collect` not being "done". I think probably the function as-is could probably be made "public". I **think** it's mostly implementation details, like the fact that internally it's mutating the command when it appends things like help-text args; and that you can't currently route a `Command` from collect into `parse`.

But neither details are really relevant to you, i think.

**Comment by pawamoy** [comment]
Awesome, thanks a lot! I think this is a rather niche use-case (for now) so the current state of the API looks fine indeed. As long as the functions are public (in the sense, not prefixed with an underscore), I'm happy with it :slightly_smiling_face: 

Feel free to close!

**Comment by pawamoy** [comment]
I'm now using this script to render my CLI usage into my docs pages:

```python
import cappa
from cappa.base import collect
from cappa.help import generate_arg_groups

from insiders.cli import CommandMain


def render_parser(command: cappa.Command, title: str, heading_level: int = 3) -> str:
    """Render the parser help documents as a string."""

    result = [f"{'#' * heading_level} **`{title}`**\n"]
    if command.help:
        result.append(f"> {command.help}\n")
    if command.description:
        result.append(f"{command.description}\n")

    for name, group in sorted(generate_arg_groups(command)):
        result.append(f"*{name.title()}*\n")
        for arg in group:
            if isinstance(arg, cappa.Subcommand):
                for option in arg.options.values():
                    result.append(
                        render_parser(option, option.real_name(), heading_level + 1)
                    )
                continue

            opts = [f"`{opt}`" for opt in arg.names()]
            if not opts:
                line = f"- `{arg.field_name}`"
            else:
                line = f"- {', '.join(opts)}"

            line += f" `{arg.value_name.upper()}`" if arg.num_args else ""
            line += f": {arg.help}"
            if arg.default is not cappa.Arg.default:
                default = str(arg.default)
                line += f" Default: `{default}`."
            result.append(line)
        result.append("")

    return "\n".join(result)


command = collect(CommandMain)
print(render_parser(command, "insiders"))
```

Here's how I define my main command:

```python
@cappa.command(name=NAME)
@dataclass(kw_only=True)
class CommandMain(HelpOption):
    """Manage your Insiders projects.

    This tool lets you manage your local and remote Git repositories
    for projects that offer an [Insiders](https://pawamoy.github.io/insiders/) version.
    """

    subcommand: An[cappa.Subcommands[CommandCreate | CommandPyPI], Doc("The selected subcommand.")]

    version: An[
        bool,
        cappa.Arg(
            short="-V",
            long=True,
            action=print_and_exit(debug.get_version),
            num_args=0,
            help="Print the program version and exit.",
        ),
    ] = False

    debug_info: An[
        bool,
        cappa.Arg(long=True, action=lambda: debug.print_debug_info(exit=True), num_args=0),
        Doc("Print debug information."),
    ] = False

    completion: An[
        bool,
        cappa.Arg(
            long=True,
            action=cappa.ArgAction.completion,
            choices=("complete", "generate"),
            help="Print shell-specific completion source.",
        ),
    ] = False
```

...and how I invoke Cappa:

```python
def main(args=None):
    output = cappa.Output(error_format=f"[bold]{NAME}[/]: [bold red]error[/]: {{message}}")
    return cappa.invoke(CommandMain,argv=args,output=output,backend=cappa.backend, completion=False, help=False)
```

Strangely, even though I add the help and completion flags explicitly to the main command, and not in `cappa.invoke`, a "Help" group still appears in the output:

![cli](https://github.com/DanCardin/cappa/assets/3999221/b9fa3664-f302-49dc-992d-7e7e72dc9abc)

Even more strangely, this Help group does not appear in the output of `insiders -h`.

Is `generate_arg_groups` adding this "Help" group?

**Comment by pawamoy** [comment]
Found it, it's the `collect` function that adds these two args. Easy fix, passing `help=False` and `completion=False` to it :slightly_smiling_face:
