### ISSUE TITLE
question: Generic class typing hint

### ISSUE THREAD

**Issue by wu-clan** [DanCardin/cappa#37]
When I use a generic classes (Arg()...), pycharm reminds me that the generic should be specified via middle brackets

Another query, how am I supposed to see the CLI content, when I run `python example.py` and it tells me: `Option 'positional_arg' requires an argument.`

**Comment by pawamoy** [comment]
Can you show us the code you have written?

**Comment by DanCardin** [comment]
Based on the name `positional_arg`, I'm going to guess you're trying to execute the example in the readme. Unfortunately the example seems to be missing a `from typing import Literal`, which may be what you meant to reference in the first bit?

For the 2nd question, try `python example.py --help`, `positional_arg` is a required positional argument in the example. In the interest of people copying the example code, I suppose I should make that optional so it works without any explicit input.

**Comment by wu-clan** [comment]
I'm very sorry for not replying in time .

I am using the MRE from the README.

Thanks for your work, as @DanCardin did, MRE now works straight away!

I am using cappa in windows and when I run `python example.py --help` it shows:

![image](https://github.com/DanCardin/cappa/assets/52145145/858e35a0-8ed3-4170-a1b7-2d7371b3359a)

There seems to be a discrepancy in the display style.

**Comment by wu-clan** [comment]
This is a type alert from PyCharm, and even though I'm using ruff, I'm sure that this alert message is not from ruff

![image](https://github.com/DanCardin/cappa/assets/52145145/6bb5cfd4-d9a1-4328-8a6c-826e9b606b27)

**Comment by DanCardin** [comment]
Seems like the latter issue is a known/reported bug against PyCharm https://youtrack.jetbrains.com/issue/PY-57155. It'd effect anything like pydantic, fastapi, PEP 727, etc. There's nothing I can really do about it unfortunately, unless you're able to disable that specific lint.
