### ISSUE TITLE
bug/question: Command and Subcommand dependencies do not work in `__call__`

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#40]
If I define a command with:

```python
@cappa.command(name="insiders")
class CommandMain:
    ...

    def __call__(self, command: cappa.Command):
        ...
```

Upon invocation I get this error:

```
cappa.invoke.InvokeResolutionError: `command: Command` is not a valid dependency for Dep(__call__).
```

I'm not sure if this is expected, as [the docs](https://cappa.readthedocs.io/en/latest/invoke.html#invoke-dependencies) don't seem to warn about that, and other dependencies like `output: cappa.Output` work fine.

---

My goal here is to avoid hardcoding subcommand names in my error message:

```python
    def __call__(self) -> int:
        if self.debug_info:
            debug.print_debug_info()
            return 0

        if not self.subcommand:
            # here
            print("insiders: Missing subcommand: create, pypi", file=sys.stderr)
            return 1

        return self.subcommand()
```

For this I wanted to get the subcommands names from the `Command` dependency. I see that I can also search into `__cappa__`, but this is internal data and I suppose I shouldn't access it:

```python
names = [
    cls.__cappa__.name
    for cls in get_type_hints(self)["subcommands"].__args__
    if isinstance(cls, cappa.Command)
]
```

**Comment by DanCardin** [comment]
I suppose the docs there are misleading. I meant the root/children user-defined dataclasses (which for you is probably less relevant since you have a `self`). So basically just an oversight.

I dont think it's **really** an issue, but i guess technically, one could want the root command versus the command being actually invoked, and type-wise there'd be no way to imply you wanted the root one. For the purposes here, I'm happy to just have it be the corresponding command though.

**Comment by pawamoy** [comment]
Thanks.

Is this even possible to list the subcommand names given a command object?

Let say I can now declare `def __call__(self, command: cappa.Command)`, how would I use `command` to list the subcommand names?

**Comment by pawamoy** [comment]
Thanks again.

Specifying an action seems to add the expectation of a positional argument:

```python
def _debug():
    debug.print_debug_info()
    raise cappa.Exit(code=0)

...
debug_info: An[bool, cappa.Arg(long=True, action=_debug), Doc("Print debug information.")] = False
```

```console
% python -m insiders --debug-info
Option 'debug_info' requires an argument.
```

**Comment by DanCardin** [comment]
hrm. My guess is that because specifying an action overrides bool inference, you might need `num_args=0`

**Comment by pawamoy** [comment]
That makes sense, thanks!

**Comment by pawamoy** [comment]
I tried to set `num_args=0` but it still tells me `Option 'debug_info' requires an argument.` :confused:

**Comment by DanCardin** [comment]
I think that's still the answer, there is just a bug concerning num_args=0 combined with custom actions 😬
