### ISSUE TITLE
question: A way to prefix/format error messages?

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#43]
Is there a way to prefix error messages or specify their format?

**Comment by DanCardin** [comment]
You could catch `Exit`, manually handle them and reraise. It depends on what your exact purpose here would be as far as what would make the most sense to recommend/add.

I've briefly thought about internationalization, which certainly doesnt exist yet and almost certainly "cant", in the argparse backend. For native backend, I'd hazard a guess that supporting this will mean adding some sub-api to the `Output` object; allowing for overriding specific error messages' format strings

**Comment by pawamoy** [comment]
`Exit` is caught inside `cappa.invoke`, so by the time I catch it in my `main` function, it's too late, messages have been printed. I guess I'd have to first parse arguments while catching `Exit`, and then invoke commands.

My goal here is simply to customize/unify the error messages a bit :slightly_smiling_face: 
For example I generally like to prefix error messages with `progname: error:`.

**Comment by DanCardin** [comment]
I'm not sure whether I see a decent middle ground here, ahead of just making all of the output strings overridable given the context that's being used to produce the output, which i think is a desirable end goal in and of itself.

"just" being a prefix would **seem** easier except that i dont see an obvious api point to make that decision. perhaps a hook into the invoke function on parse error.

**Comment by pawamoy** [comment]
I don't know the code base enough, so maybe it won't make sense at all, but I was thinking maybe something like this:

```python
cappa.invoke(
    ...,
    error_format="[bold]{prog}[/]: [bold red]error[/]: {message}",
    ...
)
```

Here `prog` and `message` are fields support by Cappa, replaced a `str.format` call. It means they support padding, suffixes, etc., anything that `str.format` supports. Maybe other fields could be supported (command(s), context, ?).

**Comment by DanCardin** [comment]
i dont hate it. although a likely more general solution, if perhaps less convenient for you, would be allow parametrization of `Output` like:

```python
output = Output(error_format="[bold]{prog}[/]: [bold red]error[/]: {message}")
cappa.invoke(..., output=output)
```
* all the output is being routed through it anyways
* it might help parse/invoke's args from growing forever.
* as I'd said above, future configurability would also likely be through Output.

on the other hand

* less convenient
* color=false is already a top-level argument (but tbh i think that's probably fine, seems more likely to be used generally?)

---
If i did this, at the same time i'd probably adjust Output's current api work with zero arguments and add builder methods for further customization (`Output().with_theme()`)

**Comment by pawamoy** [comment]
Using `Output(...)` in my main call to `cappa.invoke` sounds good to me. If we can avoid using `.from_theme(None)` (and make it a default somehow) that'd be nice too :slightly_smiling_face:

**Comment by DanCardin** [comment]
You'd be able to do `Output()` to get the default theme. or `Output(theme=x)` or `Output().with_theme(x)` to override it

**Comment by pawamoy** [comment]
Sounds perfect!

**Comment by pawamoy** [comment]
Right :thinking: I guess setting `message=""` would be OK. Otherwise maybe you can first convert the renderables to a string, and inject that in the format string:

https://github.com/Textualize/rich/issues/3152#issuecomment-1759770089

```python
from rich.console import Console

def rich_to_ansi(*messages):
    tmp_console = Console(file=None, highlight=False, color_system='standard')
    with tmp_console.capture() as capture:
        tmp_console.print(*messages, soft_wrap=True, end='')
    return capture.get()

# in Output
self.err.print(self.error_format.format(message=rich_to_ansi(*messages)))
```

**Comment by DanCardin** [comment]
i dont mind that being "hacky" since its internal, if it works (in which case thanks!) I'd run into issues a while ago trying to render console stuff and it not being straightforward to capture color output and have it render correctly on subsequent prints

**Comment by pawamoy** [comment]
Testing right now!
