### ISSUE TITLE
ux: Undetermistic "required argument" error message

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#44]
Running the same command multiple times, Cappa does not always show me the same required argument:

```console
% python -m insiders pypi register
The following arguments are required: -d, --description
% python -m insiders pypi register
The following arguments are required: -n, --name
% python -m insiders pypi register
The following arguments are required: -u, --username
% python -m insiders pypi register
The following arguments are required: -n, --name
% python -m insiders pypi register
The following arguments are required: -n, --name
% python -m insiders pypi register
The following arguments are required: -d, --description
```

By the way, should it show *all* the required arguments at once?

**Comment by DanCardin** [comment]
* non-determinism, easy to fix. just sorted the collection i'm iterating over
* whether to show all required fields at once...yes? it seems like a good idea, but raises additional UX questions on the messaging.

  I've currently got it outputting `The following arguments are required: -a/--also-required, -r/--required`, but i could imagine only outputting the long versions?

**Comment by pawamoy** [comment]
Nice!

In this particular case, I think showing both short and long options is good: the long option tells you what it does, the short option is easier to type.
