### ISSUE TITLE
question: invalid subcommand

### ISSUE THREAD

**Issue by wu-clan** [DanCardin/cappa#52]
MRE:
```python
# example.py
from __future__ import annotations
from dataclasses import dataclass
from typing import Tuple

import cappa
from cappa import Subcommand, ArgAction
from typing_extensions import Annotated  # noqa: TCH002


def print_value(value: Tuple[str, int]) -> None:
    print(value)


@dataclass
class Example:
    q: Annotated[bool, cappa.Arg(short='-q', action=ArgAction.store_true)]
    sub_a: Annotated[A | None, Subcommand(required=False)] = None
    sub_b: Annotated[B | None, Subcommand(required=False)] = None


@dataclass
class A:
    a: Annotated[str, cappa.Arg(short='-a')]


@dataclass
class B:
    b: Annotated[Tuple[str, int], cappa.Arg(short='-b', parse=print_value)]


if __name__ == '__main__':
    cappa.invoke(Example)

```
When I run `python example.py b -h`, the console prints `invalid subcommand`.

I'm not sure I'm using it correctly, and I think the parse parameter is callback-like behavior

**Comment by DanCardin** [comment]
Updated with what i think you want?

```python
# example.py
from __future__ import annotations
from dataclasses import dataclass
from typing import Tuple

import cappa
from cappa import Subcommands
from typing_extensions import Annotated  # noqa: TCH002


@dataclass
class Example:
    q: Annotated[bool, cappa.Arg(short="-q")]
    subcommand: Subcommands[A | B | None] = None


@dataclass
class A:
    a: Annotated[str, cappa.Arg(short="-a")]


@dataclass
class B:
    b: Annotated[Tuple[str, int], cappa.Arg(short="-b")]


if __name__ == "__main__":
    example = cappa.parse(Example)
    print(example)
```

```bash
$ python ex.py
Example(q=True, subcommand=None)

$ python ex.py a -a test
Example(q=True, subcommand=A(a='test'))

$ python ex.py b -b test 4
Example(q=True, subcommand=B(b=('test', 4)))
```

* you dont "need" store_true, it should be automatically inferred from the fact that it's a bool
* you **can** define `Subcommand` explicitly, but `| None = None` implies `required=False` anyways, so it can be shortened to use `Subcommands` shorthand.
* You define sibling subcommands as a single field, given that one or the other will be chosen at invocation-time
* I removed your use of `parse`. I wasn't sure what you were trying to do there. `tuple[str, int]` implies `num_args=2`, and will consume 2 cli args. `parse` **can** be used also, but you'd need to explicitly supply `num_args=2` to get the resultant tuple your type annotation implied you wanted. It also needs to return a value of the type you annotate
  * Alternatively, if you wanted to parse a single argument into two values, for example like
    ```python
    def parse_value(value: str) -> tuple[str, int]:
        left, right = value.split(',')
        return (left, int(right))
    ```
* I swapped you to `cappa.parse` (for now). you haven't define any invoke target functions (yet)

**Comment by wu-clan** [comment]
Thanks so much, I learned a lot from your instructions!

For the `parse` parameter, I initially thought it could just return the cli args, and then depending on the args, the callback function could do something other than validate the args and usually have no return value, similar to Typer.Option(callback=xxx), but you really woke me up to the fact that it's really more about validating the cli args!

Every command and sub-command is usually meant to do something, if you use invoke, it means that I have to define all the command inputs in a single function, which is probably what I've been doing wrong in Typer and click (callback performs a non-validating operation), but it's surprising that they work!

**Comment by wu-clan** [comment]
It's great. Thank you for your work.
