### ISSUE TITLE
question/bug: cappa.Arg( ) value_name format

### ISSUE THREAD

**Issue by wu-clan** [DanCardin/cappa#53]
It's working, but I found the problem, when I set `value_name='<OPENAPI JSONFILE / URL, PROJECT>'`,
it gets parsed as `<OPENAPI-JSONFILE-/-URL,-PROJECT>`, instead of the raw string.

**Comment by DanCardin** [comment]
mmm. Yea so I noticed the potential for confusion if you set `value_name` to something like 'foo bar baz`, which would render ambiguously and look like three separate args.

I suppose I can remove that dash casing and leave it up to the user to choose their value intelligently
