### ISSUE TITLE
question: cappa.Arg( ) required parse

### ISSUE THREAD

**Issue by wu-clan** [DanCardin/cappa#55]
Normally, `required=False` will be parsed to `Ellipsis` if there are no cli args, not `None`.

MRE:
```py
# example.py
from __future__ import annotations

from typing import Tuple

import cappa
from cappa import Subcommands
from typing_extensions import Annotated  # noqa: TCH002


@cappa.command(name='example')
class Example:
    q: Annotated[bool, cappa.Arg(short='-q')]
    subcommand: Subcommands[A | B | None] = None


@cappa.command(name='a')
class A:
    a: Annotated[str, cappa.Arg(short='-a', required=False)]
    c: Annotated[str, cappa.Arg(short='-c', required=False)]


@cappa.command(name='b')
class B:
    b: Annotated[Tuple[str, str], cappa.Arg(short='-b', required=False)]
    d: Annotated[None | Tuple[str, str], cappa.Arg(short='-d', required=False)]


if __name__ == '__main__':
    example = cappa.parse(Example)
    print(example.__dict__)
```
```
❯ python .\scratch.py a -a test                                           
{'q': True, 'subcommand': A(a='Ellipsis', c='Ellipsis')}

❯ python .\scratch.py b -b test 1
Invalid value for '-d' with value 'Ellipsis': 'ellipsis' object is not iterable
```

By type, if `required=False`, the correct parse should be

```py
❯ python .\scratch.py a -a test                                           
{'q': True, 'subcommand': A(a='test', c='')}

❯ python .\scratch.py b -b test 1
{'q': True, 'subcommand': B(b=('test', '1'), d=None)}
```
For more documentation on union types, in order from left to right, `None` should come first.

**Comment by wu-clan** [comment]
This may be my self-serving opinion, but actually `required` just controls whether or not the cli has to be

**Comment by wu-clan** [comment]
The default parsed values are defined by `default` or `Annotated[str, xxx] = 'test'` etc.

**Comment by DanCardin** [comment]
So, in my opinion (and from a technical perspective) there's not a generally applyable rule for defaults when you override required to False when there's no default. For example `tuple[str, str] | tuple[int, int], Arg(required=False)`.

Realistically, i think overriding `required` will usually only make sense when going the other direction. Setting it to `True`, or when explicitly setting it to false, when inference would have already enabled it to be False, i.e. `None` is in the set of available union types on the source annotation.

I think I'd just sooner disallow `required=False` in combination with lack of a default, because i do agree that `c='Ellipses'` is clearly a bug

**Comment by DanCardin** [comment]
Per the referenced PR, most of your above examples would be programmer error resulting in a `ValueError` given that there's no logical default in most cases.

I think i'm okay inferring anything that is an optional type i.e. `| None`, regardless of order, is safe to default to `None` even if the source class doesn't specify a default.

But for anything else, it'd be me making a judgement call on which types have logical defaults and what they should be. I'd rather the programmer just supply a class level one.

**Comment by wu-clan** [comment]
Hi, @DanCardin 

I tested them and they work well, it seems possible to add error location alerts, simple text descriptions don't seem to make it easy to find the source of the error

I checked out the infer_required method, and it's easy to add the error source

Do you have any thoughts on this proposal?
