### ISSUE TITLE
ux/docs: Improve error message when `Arg()` is missing a name for version argument in parse call

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#6]
With this code:

```python
    opts = cappa.parse(
        Opts,
        version=cappa.Arg(short="-V", long=True, help="Print the version of the program and exit."),
    )
```

...and this command line:

```bash
progname -V
```

...I get this error:

```python
Traceback (most recent call last):
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/bin/insiders", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/media/data/dev/insiders/insiders/src/insiders/cli.py", line 86, in main
    opts = cappa.parse(
           ^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/base.py", line 60, in parse
    _, _, instance = Command.parse_command(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/command.py", line 137, in parse_command
    _, parsed_command, parsed_args = backend(
                                     ^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/argparse.py", line 130, in backend
    version = create_version_arg(version)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/help.py", line 32, in create_version_arg
    return version.normalize(action=ArgAction.version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/arg.py", line 141, in normalize
    long = infer_long(self, origin, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/data/dev/insiders/insiders/__pypackages__/3.11/lib/cappa/arg.py", line 239, in infer_long
    long = name.replace("_", "-")
           ^^^^^^^^^^^^
AttributeError: 'ellipsis' object has no attribute 'replace'
```

It wasn't clear until I read again the docs:

> If an Arg is supplied, uses the name/short/long/help fields to add a corresponding version argument.

Then it made sense: `name` is probably `...` in Cappa's source.

If it's actually required for this usage (passing `version` with an `Arg` to `cappa.parse`), could we improve the error message to state it more clearly?

Happy to send a PR!

Also, the docs could be a tiny bit more verbose to explain how the name will be used: as the printed version. I initially thought it would be used as the program name, and then realized it didn't make sense since there would be no way to provide the actual version number :slightly_smiling_face:

**Comment by DanCardin** [comment]
Seems like a bug to me.

I'd need to write the test first to check my intuition, but probably the normalize call [here](https://github.com/DanCardin/cappa/blob/main/src/cappa/help.py#L32) should be normalizing the name in the same way help is.

I'd happily accept a PR(!), but I can also likely fix this tomorrow morning.

> Also, the docs could be a tiny bit more verbose to explain how the name will be used: as the printed version. I initially thought it would be used as the program name, and then realized it didn't make sense since there would be no way to provide the actual version number 🙂

Agreed. In both cases, the name is really mostly used internally for mapping to the source class; which should be made more clear in the docs.

**Comment by pawamoy** [comment]
I won't be able to send a PR tonight anyway :sweat_smile: Thanks a lot for your help!

**Comment by DanCardin** [comment]
oh right. upon reviewing the tests, the name is the version value for this arg, so i suppose not a bug, but just a bad error message like you said.

**Comment by DanCardin** [comment]
A better error should be emitted since v0.7.1
