### ISSUE TITLE
bug: Docstrings not used without docstring extra

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#64]
It seems #63 not only removed parsing of docstring, but also the use of docstrings altogether. #62 might have been unclear: I do want to keep documenting my subcommands using class docstrings, I just don't want them to be parsed by a docstring parser and rather just be used raw and converted from Markdown by Rich.

**Comment by pawamoy** [comment]
Actually, I'm having second thoughts about this.

To add a bit more context: my goal here is to be able to document a command *once* and be able to use this documentation as both help text for the CLI (through Cappa) and API documentation (through mkdocstrings for example).

But now that I think about it, it does not make a lot of sense. If I expose a command in my public API, it might be used by someone else with a different name or command path. Moreover, examples/instructions on how to use the command have nothing to do in the API docs.

So I think I'd be OK with using `@cappa.command(description=...)` instead of the docstring to document the command for the CLI.

**Comment by pawamoy** [comment]
So for example:

```python
@cappa.command(
    name="register",
    help="""Register a name on PyPI.""",
    description="""
    This will create a temporary project on your filesystem,
    blablabla...
    """,
)
@dataclass(kw_only=True)
class CommandPyPIRegister(HelpOption):
    """Command to register a project name on PyPI."""
```

Would it make sense to automatically dedent the description?

**Comment by DanCardin** [comment]
ah. it didn't even occur to me that the docstrings would be useful without the parser...but obviously they will be. the main usecase for even depending upon it is extracting the args.
