### ISSUE TITLE
bug: Rich markup is interpreted in docstrings

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#66]
Docstrings are rendered as Markdown. Then they're printed and Rich markup is interpreted again. It means that a docstring like this one:

```python
class Command:
    """Blabla.

    And configure `~/.pypirc`:

    ```ini
    [distutils]
    index-servers =
        pypi

    [pypi]
    username: __token__
    ```
    """
```

...will be incorrectly rendered because `[distutils]` and `[pypi]` are parsed by Rich as markup:

![markup](https://github.com/DanCardin/cappa/assets/3999221/5aa0372f-838d-4bdf-b9a2-55469ccc6983)

Locally, I tried escaping the result of `rich_to_ansi`, and it fixes the rendering:

```python
from rich.markup import escape

# in rich_to_ansi function
return escape(capture.get().strip())
```

![markupgood](https://github.com/DanCardin/cappa/assets/3999221/a162598d-2c35-4130-8abc-8ed3fa60b9bb)

---

Escaping Markdown-rendered docstrings means that one cannot use Rich markup in their docstrings. But I think it's acceptable since Rich markup clashes with Markdown syntax anyway (`[rich markup]` looks like `[markdown refs]`), and more generally it does not make a lot of sense to add more styling to Markdown-rendered text (it already has syntax for strong, emphasis,  strikethrough, link, etc.).

Can send a PR :slightly_smiling_face:

**Comment by DanCardin** [comment]
Thanks for the PR(s)!

**Comment by pawamoy** [comment]
Thanks for the super fast reviews!
