### ISSUE TITLE
ci(typing): cappa.invoke says it returns T (the passed command), but actually returns what the command returns

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#68]
With code like this:

```python
import cappa

@cappa.command()
class CommandMain:
    def __call__(self) -> int:
        return 0

def main() -> int:
    return cappa.invoke(CommandMain, ...)
```

Mypy says something like this:

```console
$ mypy src
src/insiders/cli.py:300: error: Incompatible return value type (got "CommandMain", expected "int")  [return-value]
Found 1 error in 1 file (checked 11 source files)
```

I have no idea how one could type this so that Mypy understands that `cappa.invoke` will actually have the same return type as `CommandMain.__call__` :thinking: 

Definitely not a priority to me, I can simply add a `# type: ignore[return-value]` comment.

**Comment by DanCardin** [comment]
mmm. yup i accidentally added this when making `collect` public. I think realistically there's not going to be a particularly good way to annotate the type of the return value. The return value **could** be some nested subcommand that the root command cant actually know the type of ahead of time. Ah well
