### ISSUE TITLE
question: How to add a global flag that behaves like help or version?

### ISSUE THREAD

**Issue by pawamoy** [DanCardin/cappa#7]
I want to add a global flag (`--debug-info`) that would take precedence over the rest of the arguments. I must behave like `--help` or `--version`: if found in the arguments, it calls a function and immediately exit (or just call a function that handles the exit).

Is this possible?

I have this:

```python
@dataclass
class OptsCreate:  # not important here
    """Create a pair of public/insiders repositories."""
    namespace: Annotated[str, cappa.Arg(short="-n", long=True)]


@dataclass
class Opts:
    create: Annotated[OptsCreate, cappa.Subcommand(name="create")]
    debug_info: Annotated[bool, cappa.Arg(long=True, help="Print debug information.")] = False


opts = cappa.parse(
    Opts,
    argv=args,
    help=cappa.Arg(short="-h", long=True, help="Print help and exit."),
    version=cappa.Arg(debug.get_version(), short="-V", long=True, help="Print the version of the program and exit."),
)
```

...but running `progname --debug-info` fails with:

```bash
usage: progname [--debug-info] [-h] [-V] {opts-create} ...
insiders: error: the following arguments are required: {opts-create}
```

**Comment by DanCardin** [comment]
Hrm. So there's currently no explicit way to emulate a help-like option that has specific parser precedence over other options.

There **is** the `parse` option on `Arg` which will call your given function when trying to map the original value, which could perhaps work. The primary problem there is that parsing will have finished by the time this is called, and you're seeing an error message being emitted by the parser.

But if you're using the `cappa.parse` interface, you could instead just check for `opts.debug_info` and react to that directly. In order to do that, you'd need to make create optional (`create: Annotated[OptsCreate | None, cappa.Subcommand(name="create")] = None`)

---
Sidebar, if you're coming to this from argparse/click, do you have a notion of how this would be done there? Just off the top of my head, i feel like it'd be more challenging in click, and in argparse you'd probably have a custom Action?

**Comment by pawamoy** [comment]
I see, thanks. I'd like the subcommands to remain required though :thinking: If I make them optional, I can then run `progname` without any subcommand or argument and it will not tell me a subcommand is required (showing the available subcommands).

I never used Click because I never came to like it. Your [comparison](https://cappa.readthedocs.io/en/latest/comparison.html#why-not-click) completely resonates with me.

With argparse I would make subcommands optional indeed, and I would probably add a post verification? After checking if `--debug-info` was passed, I would raise an error if no subcommand was selected. Is that possible with Cappa?

**Comment by DanCardin** [comment]
So if you were willing to make it optional, you could:

```python
opts = cappa.parse(Opts)
if opts.debug_info:
    debug.print_debug_info()
    raise Exit()

if not opts.create:
    print('Requires a subcommand')
    raise Exit(1)
```

akin to a more basic use of argparse.

---

Replicating custom actions like your above snippet has no currently available analogue.

I would hazard a guess that "the solution" will be something along the lines of `action` being able to be an arbitrary callable, except that it would expose the set of arguments sent into the action as a part of the public API, which probably wont be possible to maintain parity between the argparse parser and cappa's native one.

I'll noodle on this for a bit

**Comment by pawamoy** [comment]
OK, I'm falling in love with Cappa. This is just so simple and elegant:

```python
from __future__ import annotations

import sys
from typing import Annotated

import cappa

from insiders import debug


@cappa.command(name="create")
class CommandCreate:
    """Create a pair of public/insiders repositories."""

    namespace: Annotated[str, cappa.Arg(short="-n", long=True)]
    """Namespace of the public repository."""

    # other options removed for brevity

    def __call__(self) -> int:
        # TODO: Handle command.
        return 0


@cappa.command()
class CommandMain:
    subcommand: cappa.Subcommands[CommandCreate | None] = None
    debug_info: Annotated[bool, cappa.Arg(long=True, help="Print debug information.")] = False

    def __call__(self) -> int:
        if self.debug_info:
            debug.print_debug_info()
            return 0

        if not self.subcommand:
            # TODO: Find a way to dynamically list available commands.
            print("Missing command: create", file=sys.stderr)
            return 1

        return 0


def main(args: list[str] | None = None) -> int:
    raise SystemExit(
        cappa.invoke(
            CommandMain,
            argv=args,
            help=cappa.Arg(short="-h", long=True, help="Print help and exit."),
            version=cappa.Arg(debug.get_version(), short="-V", long=True, help="Print the version of the program and exit."),
        ),
    )
```

Each dataclass defines its own arguments, its own way of handling them in `__call__`, returns an exit code (integer) that is raised with `SystemExit` from `cappa.invoke`. All this in a single instruction in `main`.

:rocket: :sparkles: :exploding_head:

**Comment by DanCardin** [comment]
@pawamoy the linked PR relates to the inability to make your subcommand optional. I think especially for your usecase, where it accepts no arguments, the solution in the PR is actually really nice and clean, whether the rest of the feature is a good idea remains to be seen.
