### ISSUE TITLE
First class support for async invoke

### ISSUE THREAD

**Issue by thomascellerier** [DanCardin/cappa#76]
First of all thanks for cappa I have been looking for a library like that for a few years and this looks great!

I've been using it to build an internal CLI at `f"{work=}"` and am very happy with how cappa is evolving so far.
We are quite heavy users of asyncio and I think it often makes sense even for CLIs to orchestrate running various sub-commands, API calls etc...

When doing a CLI based on cappa using invoke however each and every command handler now needs a wrapper function just to call `asyncio.run`.
For example:

```Python
from __future__ import annotations

import asyncio
import dataclasses

import cappa


async def some_command(args: SomeCommand) -> None:
    print(f"Nap time, will sleep for {args.nap_time} seconds")
    await asyncio.sleep(args.nap_time)


def some_command_wrapper(args: SomeCommand) -> None:
    asyncio.run(some_command(args))


@dataclasses.dataclass
@cappa.command(invoke=some_command_wrapper)
class SomeCommand:
    nap_time: int


cappa.invoke(SomeCommand)
```

If would be nice if the wrapper could be avoided while maintaining type-safety.
One way would be to use introspection to check for a coroutine, I assume to play nice with e.g. trio the asyncio runner funciton should also be (optionally) configurable.

The resulting program could look like this:
```Python

from __future__ import annotations

import dataclasses

import cappa


async def some_command(args: SomeCommand) -> None:
    print(f"Nap time, will sleep for {args.nap_time} seconds")
    await asyncio.sleep(args.nap_time)

@dataclasses.dataclass
@cappa.command(invoke=some_command)
class SomeCommand:
    nap_time: int


cappa.invoke(SomeCommand)
```

Another option would be to add a more explicit function/parameter like `invoke_async`. More explicitly:
```Python
from __future__ import annotations


import dataclasses

import asyncio
import cappa


async def some_command(args: SomeCommand) -> None:
    print(f"Nap time, will sleep for {args.nap_time} seconds")
    await asyncio.sleep(args.nap_time)

@dataclasses.dataclass
@cappa.command(invoke_async=some_command)
class SomeCommand:
    nap_time: int


asyncio.run(cappa.invoke_async(SomeCommand))
```

Would this make sense to you?

**Comment by pawamoy** [comment]
Using `async __call__` would require detection anyway I suppose!

**Comment by DanCardin** [comment]
Thanks for the kind words!

Given your second example: `asyncio.run(cappa.invoke_async(SomeCommand))`, if that were acceptable, then as far as I can tell, just a basic async invoke function already "works" today:

```python
async def handler():
    return 5


@cappa.command(invoke=handler)
@dataclass
class Command:
    ...


@backends
def test_async_fn(backend):
    result = asyncio.run(invoke(Command, backend=backend))
    assert result == 5
```

in the sense that the top-level invoke handler calls your functions and returns the return value, a coroutine, which you can then run. right? or am i missing something.

I guess the larger issue is that ideally: explicit invoke dependencies could also be async, and fullfill themselves asynchronously, where you'd get coroutines currently.

**Comment by thomascellerier** [comment]
Thanks it does indeed work at runtime.

However mypy doesn't appreciate it:
```Python
$ python -m mypy test.py 
test.py:20: error: Argument 1 to "run" has incompatible type "SomeCommand"; expected "Coroutine[Any, Any, <nothing>]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

Given:
```Python
from __future__ import annotations


import dataclasses

import asyncio
import cappa


async def some_command(args: SomeCommand) -> None:
    print(f"Nap time, will sleep for {args.nap_time} seconds")
    await asyncio.sleep(args.nap_time)

@dataclasses.dataclass
@cappa.command(invoke=some_command)
class SomeCommand:
    nap_time: int


asyncio.run(cappa.invoke(SomeCommand))
```

So something would be needed from a type-checking perspective.

**Comment by DanCardin** [comment]
In order to properly support async dependencies (which I might as well, if I'm going to explicitly support asyncio at all), I anticipate this looking like `cappa.invoke_async`, given the way the asyncio api/libraries work.

**Comment by DanCardin** [comment]
[Docs](https://cappa.readthedocs.io/en/latest/asyncio.html), lmk if this works for you!

**Comment by thomascellerier** [comment]
Awesome, thanks for the quick response!

Just one small thing, your example is missing the top-level `asyncio.run` call, I get this error now:
```
$ python3 test.py 2
/home/thomas/Projects/asc-service-deployment/servicectl/test.py:20: RuntimeWarning: coroutine 'invoke_async' was never awaited
  cappa.invoke_async(SomeCommand)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

Fixed by adding asyncio.run on the last line, see:
```
$ cat test.py 
from __future__ import annotations


import dataclasses

import asyncio
import cappa


async def some_command(args: SomeCommand) -> None:
    print(f"Nap time, will sleep for {args.nap_time} seconds")
    await asyncio.sleep(args.nap_time)

@dataclasses.dataclass
@cappa.command(invoke=some_command)
class SomeCommand:
    nap_time: int


asyncio.run(cappa.invoke_async(SomeCommand))
```

**Comment by DanCardin** [comment]
ah yes! good catch
